main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recipes/', views.recipes_index, name='recipes_index'),
    path('recipes/<int:recipe_id>/', views.recipes_details, name='recipes_details'),
    path('recipes/create/', views.NewRecipe.as_view(), name='recipes_create'),
    path('recipes/<int:pk>/update/', views.UpdateRecipe.as_view(), name='recipes_update'),
    path('recipes/<int:pk>/delete/', views.DeleteRecipe.as_view(), name='recipes_delete'),
    path('meals/', views.meals_index, name='meals_index'),
    path('meals/<int:pk>/', views.meals_details, name='meals_details'),
    path('meals/create/', views.NewMeal.as_view(), name='meals_create'),
    path('meals/<int:pk>/update/', views.UpdateMeal.as_view(), name='meals_update'),
    path('meals/<int:pk>/delete/', views.DeleteMeal.as_view(), name='meals_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/profile/', views.profile, name='profile'),
]

mealcomplanion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.utils import timezone
from django.contrib.auth.models import User


MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner'),
    ('S', 'Snack'),
)


class Recipe(models.Model):
    name = models.CharField('Recipe Name', max_length=100)
    description = models.TextField('Description', max_length=500)
    prep_time = models.IntegerField('Prep Time (mins)')
    cook_time = models.IntegerField('Cook Time (mins)')
    servings = models.IntegerField('Number of Servings')
    serving_size = models.CharField('Serving Size', max_length=10)
    instructions = models.TextField('Instructions')
    ingredients = models.TextField('Ingredients', max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse("recipes_details", kwargs={"recipe_id": self.id})

    def get_total_time(self):
        return self.prep_time + self.cook_time


class Meal(models.Model):
    name = models.CharField('Meal Name', max_length=50)
    date = models.DateField('Meal Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    recipes = models.ManyToManyField(
        Recipe, 
        related_name='meals', 
        blank=True, 
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.date} {self.meal}'
    
    def get_absolute_url(self):
        return reverse("meals_details", kwargs={'pk': self.id})
    
    class Meta:
        ordering = ['date', "name"]

main_app/forms.py
from django.forms import ModelForm, DateInput
# from django.admin.forms import ModelMultipleChoiceField
from .models import Meal

# class TagForm(ModelForm):
#   class Meta:
#     model = Tag
#     fields = '__all__'

class MealForm(ModelForm):
  class Meta:
    model = Meal
    fields = ['name', 'date', 'meal', 'recipes']
    widgets = { "date": DateInput(format=('%m/%d/%Y'), attrs={"type": "date"})}

# class RecipeForm(ModelForm):
#   class Meta:
#     model = Recipe
#     fields = '__all__'
#     widgets = {'ingredients': ModelMultipleChoiceField
#       (Ingredient.objects.all(),
#       widget=admin.widgets.RelatedFieldWidgetWrapper(
#             widget=admin.widgets.FilteredSelectMultiple('Ingredient', False),
#             rel=Ingredients.recipes.rel,
#             admin_site=admin.site
#       ),
#       required=False,
#     )
#   }

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Recipe, Meal
from .forms import MealForm




# Route for 'Home'
def home(request):
    return render(request, 'home.html')

# Route for 'About'
def about(request):
    return render(request, 'about.html')

# Route for 'Recipes'
@login_required
def recipes_index(request):
    recipes = Recipe.objects.filter(user=request.user)
    return render(request, 'recipes/index.html', {'recipes': recipes})

# Route for 'Recipe Details'
@login_required
def recipes_details(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    return render(request, 'recipes/detail.html', {
        'recipe': recipe,
    })

# Route for 'Create Recipe'
class NewRecipe(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = ['name', 'description', 'prep_time', 'cook_time', 'servings', 'serving_size', 'ingredients', 'instructions']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

# Route for 'Updating Recipe'
class UpdateRecipe(LoginRequiredMixin, UpdateView):
    model = Recipe
    fields = ['name', 'description', 'prep_time', 'cook_time', 'servings', 'serving_size', 'ingredients', 'instructions']

# Route for 'Deleting Recipe'
class DeleteRecipe(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = '/recipes'

# Route for 'Meals'
@login_required
def meals_index(request):
    meals = Meal.objects.filter(user=request.user)
    return render(request, 'meals/index.html', {'meals': meals})

# Route for 'Meal Details'
@login_required
def meals_details(request, pk):
    meal = Meal.objects.get(id=pk)
    return render(request, 'meals/details.html', {
        'meal': meal,
    })

# Route for 'Create Recipe'
class NewMeal(LoginRequiredMixin, CreateView):
    model = Meal
    # fields = ['name', 'date', 'meal', 'recipes']
    form_class = MealForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# Route for 'Updating Recipe'
class UpdateMeal(LoginRequiredMixin, UpdateView):
    model = Meal
    fields = '__all__'

# Route for 'Deleting Recipe'
class DeleteMeal(LoginRequiredMixin, DeleteView):
    model = Meal
    success_url = '/meals'

# Route for user sign up
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('recipes_index')
    else:
        error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def profile(request):
    return render(request, 'registration/profile.html')

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="about-section">
    <h1>About Us</h1>
        <p style="text-align: center;">Here at Meal ComPLANion, we believe that cooking is an art that anyone can master. We're here to simplify the cooking process, spark your imagination, and make every meal a memorable adventure. Our mission is to empower home cooks of all skill levels to explore the world of cooking, experiment with diverse ingredients, and create exceptional dishes that tantalize the taste buds.</p>
</div>

<h2 class='team'style="text-align: center;">Our Team</h2>

<div class="row">
    <div class="column">
        <div class="img-card">
            <img src="https://images2.imgbox.com/a3/10/J8Cr8uPm_o.jpg" alt="Taylor" style="width:100%">
            <div class="container">
                <h2>Taylor Dixon</h2>
                <p class="job-title">Developer and GitHub Manager</p>
            </div>
        </div>
    </div>
    <div class="column">
        <div class="img-card">
            <img src="https://images2.imgbox.com/e4/34/8FsL708j_o.png" alt="Rodney" style="width:100%">
             <div class="container">
                <h2>Rodney Givens</h2>
                <p class="job-title">Devloper and Scrum Master</p>
            </div>
        </div>
    </div>
    <div class="column">
        <div class="img-card">
            <img src="https://images2.imgbox.com/71/58/8fdbFa5N_o.png" alt="Khi" style="width:100%">
            <div class="container">
                <h2>Khi Jackson</h2>
                <p class="job-title">Developer and Designer</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Meal ComPLANion</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <div class="wrapper">
    <header>
      <nav class="navbar">
        <div>
          <ul class="right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'recipes_create' %}">Add a Recipe</a></li>
                <li><a href="{% url 'recipes_index' %}">View All Recipes</a></li>
                <li><a href="{% url 'meals_create' %}">Add Meal</a></li>
                <li><a href="{% url 'meals_index' %}">Meal Calendar</a></li>
                <li><a href="{% url 'logout' %}">Log Out ({{ user.username }})</a></li>
            {% else %}
                <li><a href="{% url 'signup' %}">Sign Up</a></li>    
                <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>
      <div>All Rights Reserved, &copy; 2023 Meal ComPLANion &nbsp;</div>
    </footer>
</wrapper>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<head>
    <link rel="stylesheet" href="https://use.typekit.net/mtw8akb.css">
</head>
<div class="content">
    <h2 class="text-shadows">Meal Complanion</h2>
</div>
<div class="image-home">   
    <img src="https://images2.imgbox.com/72/e3/ea0tFtJu_o.png">
</div>
<div class="home-btn">
    <a href="/accounts/login" button>Let me cook!</a>
</div>
{% endblock %}

main_app/templates/main_app/meal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Meal</h1>

  <h4>Are you sure you want to delete {{ object.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'meals_details' meal.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/meal_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit {{ object.name }}</h1>
{% else %}
  <h1>Add Meal</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table class="form-tables">
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Recipe</h1>

  <h4>Are you sure you want to delete {{ object.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'recipes_details' recipe.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit {{ object.name }}</h1>
{% else %}
  <h1>Add Recipe</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table class="form-tables">
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn">Submit!</button>
</form>

{% endblock %}

main_app/templates/main_app/tag_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Tag</h1>

  <h4>Are you sure you want to delete {{ object.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' recipe.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/tag_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Tag Details</h1>


<div>
    <span class="card-title">{{ tag.name }}</span>
    <p>Color: {{ tag.color }}</p>
</div>
<div>
    <a href="{% url 'tags_update' tag.id %}">Edit</a>
    <a href="{% url 'tags_delete' tag.id %}">Delete</a>
</div>

{% endblock %}

main_app/templates/main_app/tag_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit {{ object.name }}</h1>
{% else %}
  <h1>Add Tag</h1>
{% endif %}


<form action="" method="POST">
  {% csrf_token %}
  <table class="form-tables">
    {{ form.as_table }}
  </table>
  <div class="btn-bar">
    <input type="submit" value="Submit!" class="btn">
  </div>
</form>

{% endblock %}

main_app/templates/meals/details.html
{% extends 'base.html' %}
{% block content %}

<div class="meal-details">
    <div class="mdetails-name">
        <h3>Meal Name:</h3>
        <p>{{ meal.name }}</p>
    </div>
    <div class="mdetails-recipe">
        <h3>Recipes:</h3>
        {% for recipe in meal.recipes.all %}
            <a href="{% url 'recipes_details' recipe.id %}">{{ recipe.name }}</a>
        {% endfor %}
    </div>
    <div class="mdetaiils-date">
        <h3>Meal Date:</h3>
        <p>{{ meal.date }}
    </div>
    <div class="mdetails-type">
        <h3>Meal Type:</h3>
        <p>{{ meal.get_meal_display }}</p>
    </div>
    <div class="mdetails-user">
        <h3>User</h3>
        <p>{{ meal.user }}</p>
    </div>
</div>

<div class="meal-edit-del">
    <a href="{% url 'meals_update' meal.id %}" class="edit">Edit</a>
    <a href="{% url 'meals_delete' meal.id %}" class="delete">Delete</a>
</div>
    <h3>Meal Name:</h3>
    <p>{{ meal.name }}</p>

    <h3>Recipes:</h3>
    {% for recipe in meal.recipes.all %}
        <a href="{% url 'recipes_details' recipe.id %}">{{ recipe.name }}</a>
    {% endfor %}

    <h3>Meal Date:</h3>
    <p>{{ meal.date }}

    <h3>Meal Type:</h3>
    <p>{{ meal.get_meal_display }}</p>

    
{% endblock %}

main_app/templates/meals/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Meals</h1>
    <div class="meal-container">
        {% for meal in meals.all %}
            <a href="{% url 'meals_details' meal.id %}">
                <div class="meal-card">
                    <h3>{{ meal.name }}</h3>
                    <p>Date: {{ meal.date }}</p>
                    <p>Recipe Name:  
                        {% for recipe in meal.recipes.all %}
                        {{ recipe.name }}
                    {% endfor %}</p>
                    <p>Meal: {{ meal.get_meal_display }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

main_app/templates/recipes/detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>{{ recipe.name }}</h1>
    <div class="edit-del">
    <a href="{% url 'recipes_update' recipe.id %}" class="edit">Edit</a>
    <a href="{% url 'recipes_delete' recipe.id %}" class="delete">Delete</a>
    </div>


<div class="descript-recipe">
    <div class="descript-desc">
        <h3>Description:</h3>
        <p>{{ recipe.description }}</p>
    </div>
    <div class="descript-time1">
        <h3>Prep Time:</h3>
        <p>{{ recipe.prep_time }} mins</p>
    </div>
    <div class="descript-time2">
        <h3>Cook Time:</h3>
        <p>{{ recipe.cook_time }} mins</p>
    </div>
    <div class="descript-time3">
        <h3>Total Time:</h3>
        <p>{{ recipe.get_total_time }} mins</p>
    </div>
    <div class="descript-serve">
        <h3>Servings:</h3>
        <p>Serves {{ recipe.servings }} people</p>
        <p>Total servings: {{ recipe.serving_size }}</p>
    </div>
    <div class="descript-ingredients">
        <h3>Ingredients:</h3>
        <p>{{ recipe.ingredients }}</p>
    </div>
    <div class="descript-instruct">
        <h3>Instructions:</h3>
        <p>{{ recipe.instructions }}</p>
    </div>
{% endblock %}

main_app/templates/recipes/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Recipes</h1>
    <div class="recipe-container">
        {% for recipe in recipes %}
            <a href="{% url 'recipes_details' recipe.id %}">
                <div class="recipe-card">
                    <h2>{{ recipe.name }}</h2>
                    <p>Servings: {{ recipe.servings }}</p>
                    <p>Serving Size: {{ recipe.serving_size }}</p>
                    <p>Total Time: {{ recipe.get_total_time }} mins</p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

main_app/templates/tags/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Tags</h1>
    
{% endblock %}